from PyQt4 import QtGui as qt
import os,sys
class rpm_server_list:
    def __init__(self):
        w=qt.QApplication(sys.argv)
        frame=qt.QWidget()
        label=qt.QLabel("< img src='images/back-3.jpg' height='500' width='500'>",frame)
        dns_btn=qt.QPushButton("DNS Server",frame)
        dns_btn.setFixedWidth(210)
        #dns_btn.setStyleSheet("background-color:white")
        dhcp_btn=qt.QPushButton("DHCP Server",frame)
        dhcp_btn.setFixedWidth(210)
        storage_btn=qt.QPushButton("Storage Server",frame)
        storage_btn.setFixedWidth(210)
        vertual_btn=qt.QPushButton("Virtualization",frame)
        vertual_btn.setFixedWidth(210)
        directory_btn=qt.QPushButton("Directory Server",frame)
        directory_btn.setFixedWidth(210)
        web_btn=qt.QPushButton("WEB Server",frame)
        web_btn.setFixedWidth(210)
        ftp_btn=qt.QPushButton("FTP Server",frame)
        ftp_btn.setFixedWidth(210)
        #label.move()
        dns_btn.move(145,10)
        dhcp_btn.move(145,60)
        storage_btn.move(145,110)
        vertual_btn.move(145,160)
        directory_btn.move(145,210)
        web_btn.move(145,260)
        ftp_btn.move(145,310)
        frame.setFixedSize(500,500)
        frame.setWindowTitle("RPM Packaging system")
        frame.setWindowIcon(qt.QIcon("images/logo128x128.png"))
        frame.setGeometry(100,100,500,500)
        frame.show()
        w.exec_()
o=rpm_server_list()
